### ISSUE TITLE
Move MMIO region registration to the guest

### ISSUE THREAD

**Issue by abrestic-rivos** [rivosinc/salus#104]
As @atishp04 and I have found, the other confidential compute implementations (pKVM, TDX, SEV) have the TVM decide what's MMIO and what isn't -- pKVM registers the regions via hypercalls, TDX & SEV have a more convoluted scheme where a page fault gets reflected back to the TVM which it can then turn into a hypercall. So, let's make `tvm_add_emulated_mmio_region()` a guest-side SBI call in a separate TEE-Guest extension to be consistent and avoid having to introduce our own KVM `ioctl()` to register MMIO registers on the host side.

We should probably also do the same with shared memory. The host can tell the TVM via device-tree or whatever where it wants the shared memory region to be, and then the guest effectively "accepts" that as the shared memory region by making a `tvm_add_shared_memory_regino()` SBI call.

In both cases we can notify the host that the TVM has registered these regions by setting up the shared-memory block to look like an ECALL exit from the TVM.

**Comment by atishp04** [comment]
Cc @rsahita to get his opinion about this approach compared to x86/AMD

**Comment by dgreid** [comment]
> As @atishp04 and I have found, the other confidential compute implementations (pKVM, TDX, SEV) have the TVM decide what's MMIO and what isn't -- pKVM registers the regions via hypercalls, TDX & SEV have a more convoluted scheme where a page fault gets reflected back to the TVM which it can then turn into a hypercall. So, let's make `tvm_add_emulated_mmio_region()` a guest-side SBI call in a separate TEE-Guest extension to be consistent and avoid having to introduce our own KVM `ioctl()` to register MMIO registers on the host side.
> 
> We should probably also do the same with shared memory. The host can tell the TVM via device-tree or whatever where it wants the shared memory region to be, and then the guest effectively "accepts" that as the shared memory region by making a `tvm_add_shared_memory_regino()` SBI call.

Seems good to me. If there is a unanimous direction we should follow it.

> 
> In both cases we can notify the host that the TVM has registered these regions by setting up the shared-memory block to look like an ECALL exit from the TVM.

Can you explain this further? Which shared memory block will be used to simulate an ECALL?

**Comment by atishp04** [comment]
> In both cases we can notify the host that the TVM has registered these regions by setting up the shared-memory block to look like an ECALL



> > As @atishp04 and I have found, the other confidential compute implementations (pKVM, TDX, SEV) have the TVM decide what's MMIO and what isn't -- pKVM registers the regions via hypercalls, TDX & SEV have a more convoluted scheme where a page fault gets reflected back to the TVM which it can then turn into a hypercall. So, let's make `tvm_add_emulated_mmio_region()` a guest-side SBI call in a separate TEE-Guest extension to be consistent and avoid having to introduce our own KVM `ioctl()` to register MMIO registers on the host side.
> > We should probably also do the same with shared memory. The host can tell the TVM via device-tree or whatever where it wants the shared memory region to be, and then the guest effectively "accepts" that as the shared memory region by making a `tvm_add_shared_memory_regino()` SBI call.
> 
> Seems good to me. If there is a unanimous direction we should follow it.
> 

Just to add more context, TDX/SEV approach seems to be set in stone. But the PKVM approach may change in the future as the series[1] has not been revised since last year. The mega pkvm series[2] does mention 

"Support for restricted MMIO exits to only regions designated as MMIO by the guest. An earlier version of this work was previously posted at [4]."

The commit text in [1] indicates that Marc is not particularly happy with the ioremap hooks.

[1] https://lore.kernel.org/all/20211004174849.2831548-1-maz@kernel.org/
[2] https://lwn.net/Articles/895790/

I guess the series may evolve to improve the plumbing of MMIO regions from the guest. However, the general consensus is towards the guest decides which region is MMIO instead of the host.

> > In both cases we can notify the host that the TVM has registered these regions by setting up the shared-memory block to look like an ECALL exit from the TVM.
> 
> Can you explain this further? Which shared memory block will be used to simulate an ECALL?

**Comment by abrestic-rivos** [comment]
>>In both cases we can notify the host that the TVM has registered these regions by setting up the shared-memory block to look like an ECALL exit from the TVM.
>
>Can you explain this further? Which shared memory block will be used to simulate an ECALL?

In the vCPU shared state block that's used to communicate the exit status.

Example:
- Guest calls `tee_guest_add_mmio_region()`
- TSM validates the parameters and adds the specified region to the list of MMIO regions for the guest
- TSM updates the guest's shared state area to make it appear as if the guest exited to the `tee_guest_add_mmio_region()` call (e.g. scause = ECALL, a0 = address, and so on)
- TSM returns to the host. This guest's exit status is purely informational to the host; the host cannot use this to communicate anything back to the guest.
- Next time the host runs it resumes at the instruction following the ECALL.

**Comment by dgreid** [comment]
> Example:
> 
> * Guest calls `tee_guest_add_mmio_region()`
> * TSM validates the parameters and adds the specified region to the list of MMIO regions for the guest
> * TSM updates the guest's shared state area to make it appear as if the guest exited to the `tee_guest_add_mmio_region()` call (e.g. scause = ECALL, a0 = address, and so on)
> * TSM returns to the host. This guest's exit status is purely informational to the host; the host cannot use this to communicate anything back to the guest.
> * Next time the host runs it resumes at the instruction following the ECALL.

Thanks, got it. Could the host notice an error in the setup if the TVM assigned unknown regions as MMIO? assuming the MMIO regions are for emulated devices that host must know about.

**Comment by atishp04** [comment]
> > Example:
> > 
> > * Guest calls `tee_guest_add_mmio_region()`
> > * TSM validates the parameters and adds the specified region to the list of MMIO regions for the guest
> > * TSM updates the guest's shared state area to make it appear as if the guest exited to the `tee_guest_add_mmio_region()` call (e.g. scause = ECALL, a0 = address, and so on)
> > * TSM returns to the host. This guest's exit status is purely informational to the host; the host cannot use this to communicate anything back to the guest.

What will the host(KVM) do with that information unless it forwards it to the userspace?

> > * Next time the host runs it resumes at the instruction following the ECALL.
> 
> Thanks, got it. Could the host notice an error in the setup if the TVM assigned unknown regions as MMIO? assuming the MMIO regions are for emulated devices that host must know about.

KVM doesn't have that information for devices emulated in the userspace. For device emulated in kernel, it can do a validation.

**Comment by atishp04** [comment]
Another thought: Do we need an tee_guest_remove_mmio_region() as well ? PkVM have a similar hypercall.
Probably needed to allow hot plugging of devices ?

**Comment by abrestic-rivos** [comment]
> What will the host(KVM) do with that information unless it forwards it to the userspace?

So it knows to expect to be able to forward page faults in that region to userspace with a valid instruction in htinst. It doesn't have to do anything with this information either, but providing that information gives KVM (or whatever other hypervisor) the flexibility in case it does want to do something.

> Another thought: Do we need an tee_guest_remove_mmio_region() as well ? PkVM have a similar hypercall.
Probably needed to allow hot plugging of devices ?

Probably.

**Comment by atishp04** [comment]
> * tee_guest_add_mmio_region



> > What will the host(KVM) do with that information unless it forwards it to the userspace?
> 
> So it knows to expect to be able to forward page faults in that region to userspace with a valid instruction in htinst. It doesn't have to do anything with this information either, but providing that information gives KVM (or whatever other hypervisor) the flexibility in case it does want to do something.

TSM must have done the validation already. The host can continue to do what it is doing now. Treat any page fault beyond guest RAM region as MMIO faults. That's why host doesn't have to be aware of the mapped guest MMIO region.

Let's say we want to provide that information to the host to be flexible (in case any hypervisor in future wants to leverage that information).

vcpu_run exists with the following state 
scause = ECALL, a0 = address 
What would be there in a7 (extension ID) ? If it is an invalid value, the host simply would ignore this and proceed.
Do you intend the fill the exit status(MMIO_MAPPED or something similar) in sbiret from vcpu_run? 
Your latest PR removed all the exit cause.

May be I missed something ?

> 
> > Another thought: Do we need an tee_guest_remove_mmio_region() as well ? PkVM have a similar hypercall.
> > Probably needed to allow hot plugging of devices ?
> 
> Probably.

**Comment by abrestic-rivos** [comment]
> TSM must have done the validation already. The host can continue to do what it is doing now. Treat any page fault beyond guest RAM region as MMIO faults. That's why host doesn't have to be aware of the mapped guest MMIO region.

Yes, like I said it's not for host validation purposes; it's purely informational.

> Let's say we want to provide that information to the host to be flexible (in case any hypervisor in future wants to leverage that information).
>
> vcpu_run exists with the following state
scause = ECALL, a0 = address
What would be there in a7 (extension ID) ?

Assuming the SBI call is, say, `tee_guest_add_mmio_region(unsigned long addr, unsigned long len)`, the register state would look like:
- scause = ECALL
- a0 = `addr`
- a1 = `len`
- a2 through a5 = 0
- a6 = <extension ID for `TEE_GUEST`>
- a7 = <function ID for `add_mmio_region()`>

**Comment by atishp04** [comment]
Ahh got it. I forgot about the TEE_GUEST extension.

**Comment by dgreid** [comment]
On Wed, Sep 21, 2022 at 06:34:31PM -0700, Andrew Bresticker wrote:
> As @atishp04 and I have found, the other confidential compute implementations (pKVM, TDX, SEV) have the TVM decide what's MMIO and what isn't -- pKVM registers the regions via hypercalls, TDX & SEV have a more convoluted scheme where a page fault gets reflected back to the TVM which it can then turn into a hypercall. So, let's make `tvm_add_emulated_mmio_region()` a guest-side SBI call in a separate TEE-Guest extension to be consistent and avoid having to introduce our own KVM `ioctl()` to register MMIO registers on the host side.
> 
> We should probably also do the same with shared memory. The host can tell the TVM via device-tree or whatever where it wants the shared memory region to be, and then the guest effectively "accepts" that as the shared memory region by making a `tvm_add_shared_memory_regino()` SBI call.

This seems good to me.

> 
> In both cases we can notify the host that the TVM has registered these regions by setting up the shared-memory block to look like an ECALL exit from the TVM.

Which shared-memory block is going to look like an ECALL? Do you mean
access to the shared memory block?
