### ISSUE TITLE
Compile with vector support enabled by default

### ISSUE THREAD

**Issue by abrestic-rivos** [rivosinc/salus#125]
Looks like we don't need a separate target for this and can instead add `-Ctarget-feature=+v` to `.cargo/config`:

```
[target.riscv64gc-unknown-none-elf]
rustflags = [
    '-Clink-arg=-Tlds/qemu.lds',
    '-Ctarget-feature=+v',
    # new in 1.60 and generates false positives
    "-Aclippy::only_used_in_recursion",
]
````

This would allow us to get rid of the conditional compilation that's littered around for vector support, giving us better compile-time coverage.

Two issues I noticed when running with `+v` enabled (on a non-V enabled QEMU config):
- `check_vector_width()` runs unconditionally. It should be guarded based on whether we detected vector support.
- Tellus unconditionally exercises vector save/restore. It should check if vectors are supported first, preferably via DT.

cc @stillson

**Comment by stillson** [comment]
I'm on this.
