### ISSUE TITLE
make run_buildroot stuck at boot

### ISSUE THREAD

**Issue by wangzhankun** [rivosinc/salus#237]
As shown in the following image, I cannot interact with the Linux. No output and cannot input anything.

![image_319](https://user-images.githubusercontent.com/35724924/218077661-cefee897-74d2-49fb-a2ac-410350b3b417.png)

**Comment by wangzhankun** [comment]
Must use ssh.

 `ssh -p 7722 root@localhost`

 Password is `root`

**Comment by abrestic-rivos** [comment]
As you've noticed the console is read-only; the SBI debug-console extension only supports console output, not input. So SSH'ing is indeed the intended way to interact with the system.
