### ISSUE TITLE
Debian on Salus not responding to input, terminal frozen

### ISSUE THREAD

**Issue by GDHNES** [rivosinc/salus#265]
I'm experiencing an issue while trying to run Debian on Salus. When I try to start it up, the terminal freezes and I am unable to input any commands or navigate through the system. I've checked that all the prerequisites have been set up according to the instructions, and all other examples seem to work fine.The snapshot for frozen terminal is like:
![image](https://user-images.githubusercontent.com/34539056/222355804-256f5b38-c699-497c-b56a-730d9775abd3.png)

My current environment is:
- Commit: 95d2fd887bad90b0be9c2d23eab668fe82b6872c
- Kernel: Linux 5.4.0-139-generic x86_64
- QEMU: QEMU emulator version 7.1.50
- CPU: i7-10875h
- RAM: 24G

Is there something I might have missed or done incorrectly during the setup process? How can I solve this issue?

Steps to Reproduce:

1. Follow the instructions for setting up Debian on Salus(riscv64-virt image downloaded from https://people.debian.org/~gio/dqib/)
2. Try to run Debian("make run_debian ...")
3. Observe that the terminal freezes and does not respond to any input

Expected Behavior:
  Debian should run normally without any issues and respond to input from the terminal.
Actual Behavior:
  The terminal freezes and does not respond to any input, preventing me from using Debian.

Additional Notes:
I've tried searching for similar issues online, but I haven't found anything that matches this exact problem. I appreciate any help or suggestions to solve this issue. Thank you.

**Comment by rbradford** [comment]
Did you try SSHing in (like the instructions suggest.)? I don't think there is a getty running on the console you see.

**Comment by GDHNES** [comment]
> Did you try SSHing in (like the instructions suggest.)? I don't think there is a getty running on the console you see.

I did try SSH. Actually running the Buildroot example will also stuck my console, I manage to connect to the guest machine via SSH, but it just doesn't work for Debian. It will always end like this:

- ~$ ssh 127.0.0.1 -l root -p 2222
- ssh: connect to host 127.0.0.1 port 2222: Connection refused

**Comment by GDHNES** [comment]
> Did you try SSHing in (like the instructions suggest.)? I don't think there is a getty running on the console you see.

I did try SSH. Actually running the Buildroot example will also stuck my console, I manage to connect to the guest machine via SSH, but it just doesn't work for Debian. It will always end like this:

- ~$ ssh 127.0.0.1 -l root -p 2222
- ssh: connect to host 127.0.0.1 port 2222: Connection refused

**Comment by abrestic-rivos** [comment]
> ssh: connect to host 127.0.0.1 port 2222: Connection refused

Because you're using the wrong port, assuming you're using the `make run_debian` target. It's 7722.

Also console input not working is expected. Salus owns the UART device and the host writes to it using the SBI debug console extension. The debug console extension is for output only.

**Comment by GDHNES** [comment]
> > ssh: connect to host 127.0.0.1 port 2222: Connection refused
> 
> Because you're using the wrong port, assuming you're using the `make run_debian` target. It's 7722.
> 
> Also console input not working is expected. Salus owns the UART device and the host writes to it using the SBI debug console extension. The debug console extension is for output only.

Thanks for your reply, Andrew. It works after the port was set to 7722. I use port 2222 because the readme.txt in somewhere/dqib_riscv64-virt says:

```
You can login with root:root or debian:debian, or using the identities ssh_user_*_key in this directory.
You can also login with SSH on the local port 2222 (this will give you a much better terminal emulation than the QEMU default).
```

That is a little bit misleading, nonetheless, this problem has been solved. Besides, I didn't know about the UART things, thanks for your hint!😉
