### ISSUE TITLE
gdb debugging 

### ISSUE THREAD

**Issue by yli147** [rivosinc/salus#320]
I'm trying to use gdb to debug with the bazel-bin/salus, some steps are as below, but it looks like the gdb can't find the the source code for example main.rs based on symbol file bazel-bin/salus.  Has anyone one worked with gdb ? Thanks 

$ gdb-multiarch bazel-bin/salus
$ set architecture riscv:rv64
$ target remote localhost:1234
$ set directories ./src/
$ add-symbol-file ./bazel-bin/test-workloads/guestvm
$ add-symbol-file ./bazel-bin/test-workloads/tellus

**Comment by yli147** [comment]
Hi Rajnesh, Thanks for your response, still not working even by using "gdb-multiarch --symbols=bazel-bin/salus",  what's the version of your rust toolchain and gdb ? or anything other ?

![image](https://user-images.githubusercontent.com/21300636/236467255-0f698b20-0355-4598-ad2a-698448a150fd.png)

**Comment by yli147** [comment]
And Yes, guest application debugging is not available right after the sret instruction

![image](https://user-images.githubusercontent.com/21300636/236468385-e7b0fb15-a0ce-43de-ab11-d5efb5f7262a.png)

**Comment by rajnesh-kanwal** [comment]
> gdb-multiarch -v
> GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2

Strange. These seems to work fine for me.

![image](https://user-images.githubusercontent.com/72204611/236471092-bcd1ce0f-e9ba-4216-96c9-9af6e6fc8ef4.png)

**Comment by yli147** [comment]
I'm using the below commands to build salus, is there anything wrong ?  By the way I can debug one riscv hello world application written by rust.   so now I guess it should not the gdb issue.   Are there any build option to force to build  a debug version of salus ? Thanks 

$ git clone https://github.com/rivosinc/salus.git
$ cd salus/
$ git submodule update --init
$ wget -c https://github.com/bazelbuild/bazelisk/releases/download/v1.16.0/bazelisk-linux-amd64
chmod a+x bazelisk-linux-amd64
$ ./bazelisk-linux-amd64 build //:salus-all
$ {QEMU}/build/riscv64-softmmu/qemu-system-riscv64 \
    -M virt,aia=aplic-imsic,aia-guests=4 -cpu rv64,v=on,vlen=256,elen=64,x-smaia=true,x-ssaia=true,sscofpmf=true -smp 1 -m 2048 -nographic \
    -kernel bazel-bin/salus \
    -device guest-loader,kernel=bazel-bin/test-workloads/tellus_guestvm,addr=0xc0200000 -s -S

**Comment by yli147** [comment]
Oh,   it is caused by the --compilation_mode, with the below change, I can debug the salus now ! Thanks 

$ vim ./.bazelrc
 Change the 
 build --compilation_mode=opt
 =>
 build --compilation_mode=dbg

**Comment by yli147** [comment]
By the way,  I can also debug the guest application by using the following steps:

$ gdb-multiarch --symbols=bazel-bin/salus
$ set architecture riscv:rv64
$ target remote localhost:1234
$ b _run_guest
$ b _guest_exit
$ c
It will stop in _run_guest, then step to the sret instruction
$ b *0x80200000
$ c
it will stop at 0x80200000 which is of the guest application
$ remove-symbol-file -a 0x80200000
$ add-symbol-file ./bazel-bin/test-workloads/tellus
$ b tellus.rs:464
$ c

![image](https://user-images.githubusercontent.com/21300636/236607685-ad007e2a-da68-4833-872b-13d1aad416f8.png)

**Comment by rajnesh-kanwal** [comment]
> Oh, it is caused by the --compilation_mode, with the below change, I can debug the salus now ! Thanks
> 
> $ vim ./.bazelrc Change the line build --compilation_mode=opt => build --compilation_mode=dbg

You can avoid all this by using `make run_tellus_gdb`, it takes care of everything, including invoking qemu with `-s -S` options.

**Comment by yli147** [comment]
ok, thanks !
